services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      DB_URL: jdbc:postgresql://postgres:5432/pj2
#      DB_USER: user
#      DB_PASSWORD: password
#    depends_on:
#      - postgres
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pj2
    ports:
      - "5454:5432"